#!/usr/bin/env python
import sys
import argcomplete

# from util.constants import *
from manager.CLI.manager_parser import setup_parser


def main(argv):
    parser = setup_parser()
    args = parser.parse_args(argv)
    argcomplete.autocomplete(parser)


if __name__ == "__main__":
    main(sys.argv[1:])



