#!/usr/bin/env python
import sys
import argcomplete

from CLI.manager_parser import setup_parser
from util.json_helper import load_json_from_file, save_json_to_file


def main(argv):
    parser = setup_parser()
    args = parser.parse_args(argv)
    argcomplete.autocomplete(parser)

    if args.operation is None:
        print("You need to choose an operation")
    else:
        if hasattr(args, 'func'):
            args.func(args)
        else:
            parser.print_help()


if __name__ == "__main__":
    main(sys.argv[1:])
